# Generated by Django 5.1 on 2024-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbx_call_id', models.CharField(db_index=True, max_length=56)),
                ('call_id_with_rec', models.CharField(blank=True, db_index=True, max_length=56, null=True)),
                ('caller_id', models.CharField(db_index=True, max_length=36)),
                ('caller_phone', models.CharField(db_index=True, max_length=36)),
                ('call_start_time', models.DateTimeField(blank=True, null=True)),
                ('call_end_time', models.DateTimeField(blank=True, null=True)),
                ('destination_number', models.CharField(db_index=True, max_length=36)),
                ('call_type', models.CharField(db_index=True, max_length=36)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status_code', models.CharField(db_index=True, max_length=36)),
                ('is_recorder', models.BooleanField(default=False)),
                ('disposition', models.CharField(db_index=True, max_length=36)),
                ('caller_record_link', models.URLField(blank=True, null=True)),
                ('events', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
