# Generated by Django 5.1 on 2024-09-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_callrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call_type',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='caller_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='caller_phone',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='destination_number',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='disposition',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='status_code',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
