# Generated by Django 5.1 on 2024-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_callrecord_call_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='events',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
